"""empty message

Revision ID: 2332f08e9430
Revises: da4cfbe1c023
Create Date: 2021-03-02 23:10:17.020444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2332f08e9430'
down_revision = 'da4cfbe1c023'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('deezer_tkn', sa.String(length=1000), nullable=True))
    op.add_column('users', sa.Column('soundcloud_tkn', sa.String(length=1000), nullable=True))
    op.add_column('users', sa.Column('spotify_tkn', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'spotify_tkn')
    op.drop_column('users', 'soundcloud_tkn')
    op.drop_column('users', 'deezer_tkn')
    # ### end Alembic commands ###
