"""empty message

Revision ID: 2c64078d1aff
Revises: 635e91180d41
Create Date: 2021-03-04 20:03:25.441608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c64078d1aff'
down_revision = '635e91180d41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('soundcloud_tkn', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'soundcloud_tkn')
    # ### end Alembic commands ###
