"""empty message

Revision ID: 343ddfc5742c
Revises: 2c64078d1aff
Create Date: 2021-03-04 22:45:09.791455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '343ddfc5742c'
down_revision = '2c64078d1aff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'soundcloud_tkn')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('soundcloud_tkn', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
